name: "EcoFlow Keepalive"
description: "Headless keep-alive for EcoFlow user portal"
version: "1.0.4"
slug: "ecoflow_keepalive"
init: false
arch:
  - aarch64
  - amd64
options:
  email: ""
  password: ""
schema:
  email: str
  password: password
startup: application
boot: auto
map:
  - config:ro
